[package]
name = "urt"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
slab = "0.4.6"
io-uring = "0.5.2"
tokio = { version = "1.18.2", features = ["sync"] }
crossbeam-channel = "0.5.5"
libc = "0.2.126"
parking_lot = "0.12.1"
hashbrown = "0.12.2"

[profile.release]
debug = true